### ISSUE TITLE
Script output should integrate with anaconda-server

### ISSUE THREAD

**Issue by srossross** [Anaconda-Server/anaconda-build#86]
Right now the script output is just flat text. It would be great to have better reporting 

Some examples: 

 1. What command failed? highlight the bad command in red in the job page.

**Comment by PeterDSteinberg** [comment]
A nice addition to this PR, when it is created, would be to allow users to define a data tag word that can be used for printing structured data to be parsed. For example, if my build script prints:

```
my_tag {"builds: 8}
```
and my `.binstar.yml` says
```
datatag: my_tag
```
Then the build script output parser can accumulate a user data list of all such print statements, e.g. `[{"builds": 8}]` if there was only one print statement.

**Comment by PeterDSteinberg** [comment]
Plan:

 * build_script.bat and build_script.sh:
  * make tags for each section that is running `echo '###RUNNING_SECTION### <tag for section name>'`
  * make metadata json generator about all the tags that can be generated so that Repo UI can do different things for each tag, like font styles
 * build process wrappers in Python:
   * look for `###RUNNING_SECTION some_section_name` while polling build process and accumulating build log
   * note in which section_tag the build was running when the return code of the build process became nonzero
  * look for the `datatag` defined in .binstar.yml for user data (see comment above this one in this issue) and accumulate user data on the Repo side
   * keep the current system of plain build logs intact for backwards compat
   * make sure the section_tag that is running is passed to Server UI when passing build log sections
   * Server UI store and present build logs by section_tag

**Comment by srossross** [comment]
@PeterDSteinberg this sounds great.

**Comment by srossross** [comment]
we should be able to do this on the client independently of the server, since the build logging  endpoint will just ignore tags to start.

**Comment by PeterDSteinberg** [comment]
Changed the milestone to 0.14.1 -> that is inclusive of only the build (backend) part of these changes, not the Server UI improvements that go along with it thereafter.

**Comment by dsludwig** [comment]
Fixed by https://github.com/Anaconda-Server/anaconda-build/pull/238 and https://github.com/Anaconda-Server/anaconda-server/pull/1730

**Comment by dsludwig** [comment]
This will be released with Anaconda Repo 2.17.
